jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - continue-on-error: true
      name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Ant build
      run: ant -noinput -buildfile build.xml clean check jar unittest
    - continue-on-error: true
      name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: openrocket_build_${{ github.run_number }}
        path: ${{github.workspace}}/swing/build/jar/OpenRocket.jar
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
